apiVersion: v1
kind: Service
metadata:
    name: "adkubernetescluster-a3fb"
    labels:
        app: "adkubernetescluster-a3fb"
spec:
    type: LoadBalancer
    ports:
    - port: 809
      targetPort: 809
      protocol: TCP
      name: http
    selector:
        app: "adkubernetescluster-a3fb"